stages:
  - test
  - build

variables:
  CCACHE_DIR: "$CI_PROJECT_DIR/.ccache"
  CCACHE_BASEDIR: "$CI_PROJECT_DIR"
  CCACHE_COMPRESS: "1"
  CCACHE_COMPRESSLEVEL: "9"

default:
  image: registry.gitlab.com/signal9/cpp-env:squashed
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .conan
      - .ccache
  before_script:
    - conan remote add signal9 https://api.bintray.com/conan/signal9/conan --insert
    - conan config set storage.path="$CI_PROJECT_DIR/.conan"

test:
  stage: test
  script:
    - make check/format
    - make build/cov
    - make check/tidy
    - make test
    - make check/cov

build:
  stage: build
  artifacts:
    paths:
      - dist
    expire_in: 1 day
  script:
    - make release
    - make install
