build:
  image: registry.gitlab.com/signal9/cpp-env:squashed
  stage: build
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .conan
      - .ccache
  artifacts:
    paths:
    - dist
    expire_in: 1 day
  variables:
    CCACHE_DIR: "$CI_PROJECT_DIR/.ccache"
  before_script:
    - conan remote add signal9 https://api.bintray.com/conan/signal9/conan
    - conan config set storage.path="$CI_PROJECT_DIR/.conan"
  script:
    - make release
    - build/angonoka_test
    - make install
