stages:
  - test
  - build

variables:
  CCACHE_DIR: "$CI_PROJECT_DIR/.ccache"
  CCACHE_BASEDIR: "$CI_PROJECT_DIR"
  CCACHE_COMPRESS: "1"
  CCACHE_COMPRESSLEVEL: "9"

default:
  image: registry.gitlab.com/signal9/cpp-env:squashed
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .conan
      - .ccache
  before_script:
    - conan remote add signal9 https://api.bintray.com/conan/signal9/conan --insert
    - conan config set storage.path="$CI_PROJECT_DIR/.conan"
    - |
      base64 -d <<EOF | zcat > ~/.conan/settings.yml
      H4sIAAAAAAAAA61QTWvDMAy9+1eY9tgw6lK6LudeBm0P62CHEYLjaKnBtY0/RrpfP9lmyd
      h5BvGen54lWca3XZSqr+n7Ueo4NoQ7cZ20cb9rd9uGGN8G7gYIf3yTOBtrQvFkU51Nv7LC
      3KxU4IpHKK6HQtP5BOel0WhfMLZoJl3JTowjyomsVnNCWOtDmvJsNFT0aV/RQccEjGWagG
      0LRWCPhSJs1plu1nM1F3WQN5jKnQ4Yryn6dOkbkpfShrudTQfo4lDRF1DAPWTyJsMV5Wf9
      YfCd1Bf5BSjj5/9jXEqX2NQ6EDwADhY90J+tPpQO5BtVYOkg1AEAAA==
      EOF

test:
  stage: test
  script:
    - make check-format
    - make build-cov
    - make check-tidy
    - make test
    - make check-cov

build:
  stage: build
  artifacts:
    paths:
      - dist
    expire_in: 1 day
  script:
    - make release
    - make install
