stages:
  - test
  - build

variables:
  CCACHE_DIR: "$CI_PROJECT_DIR/.ccache"
  CCACHE_BASEDIR: "$CI_PROJECT_DIR"
  CCACHE_LOGFILE: "$CI_PROJECT_DIR/ccache.log"
  CCACHE_COMPRESS: "1"
  CCACHE_COMPRESSLEVEL: "9"
  CCACHE_SLOPPINESS: "system_headers,locale,include_file_ctime,include_file_mtime,time_macros"
  ASAN_OPTIONS: "alloc_dealloc_mismatch=0"

default:
  image: registry.gitlab.com/signal9/cpp-env:13.0.0
  cache:
    key: "$CI_COMMIT_REF_SLUG-$CI_JOB_NAME"
    paths:
      - .ccache
  before_script:
    - conan remote add signal9 https://signal9.jfrog.io/artifactory/api/conan/conan --insert
    - conan config set general.revisions_enabled=1
    - make check/format
    - export CCACHE_DISABLE=1
    - make build/conaninfo.txt
    - unset CCACHE_DISABLE
  after_script:
    - ccache --show-stats
    - |
      to_delete="$(sed -En '/(Retrieved|Stored)/s/.*\((.*)\)/\1/gp' $CCACHE_LOGFILE | sort -u)
      $(find $CCACHE_DIR -type f)"
      to_delete=$(echo "$to_delete" | sort | uniq -u)
      if [[ -n "$to_delete" ]]; then
        rm $to_delete
        count_deleted=$(echo "$to_delete" | wc -l)
        echo "Removed $count_deleted cache entries"
      fi


test:
  stage: test
  script:
    - make build/cov
    - make test
    - pip install --no-cache-dir pytest
    - make test/functional
    - make check/cov

clang-tidy:
  stage: test
  script:
    - ln -sf /usr/bin/python{3,}
    - make check/tidy

build:
  stage: build
  artifacts:
    paths:
      - dist
      - debug
    expire_in: 1 day
  script:
    - make release
    - make install
