stages:
  - test
  - build

variables:
  CCACHE_DIR: "$CI_PROJECT_DIR/.ccache"
  CCACHE_BASEDIR: "$CI_PROJECT_DIR"
  CCACHE_COMPRESS: "1"
  CCACHE_COMPRESSLEVEL: "9"

default:
  image: registry.gitlab.com/signal9/cpp-env:12.0.0
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .conan
      - .ccache
  before_script:
    - conan remote add signal9 https://signal9.jfrog.io/artifactory/api/conan/conan
    - conan config set general.revisions_enabled=1
    - conan config set storage.path="$CI_PROJECT_DIR/.conan"
  after_script:
    - conan remove -b -s -f '*'

test:
  stage: test
  script:
    - make check/format
    - make build/cov
    - make test
    - pip install --no-cache-dir pytest
    - make test/functional
    - make check/cov

clang-tidy:
  stage: test
  script:
    - make check

build:
  stage: build
  artifacts:
    paths:
      - dist
      - debug
    expire_in: 1 day
  script:
    - make release
    - make install
